# Generated by Django 3.1.5 on 2021-01-04 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('prop', models.TextField(blank=True, default=[], null=True)),
            ],
        ),
        migrations.CreateModel(
            name='results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_data', models.TextField(blank=True, default={}, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('quiz_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizz_app.quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True, default='', null=True)),
                ('mcq', models.TextField(blank=True, default=[], null=True)),
                ('answer', models.TextField(blank=True, default=[], null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('quiz_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizz_app.quiz')),
            ],
        ),
    ]
